openapi: 3.0.1
x-stoplight:
  id: kbgyppvu32fiv
info:
  title: Current Account
  description: 'This service domain orchestrates a consumer checking/demand deposit account. The typical range of services and fees covers payments and deposits, standing orders, sweeps, liens, check and debit card access.'
  contact:
    name: C4E
    email: Dharamveer.1985@gmail.com
    url: 'https://www.demo.co.nz'
  version: 11.0.0
  license:
    url: 'https://www.demo.co.nz'
    name: Demo
servers:
  - url: 'https://virtserver.swaggerhub.com/current-account/api'
paths:
  /current-account:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Schema/GetCurrentAccount.yaml
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      operationId: get-current-account
      x-stoplight:
        id: 56dotah8tv67d
      description: Retrieve Information about the Current Account
      tags:
        - GetCurrentAccount
      x-internal: false
      requestBody:
        content: {}
    post:
      summary: create a new current
      operationId: post-current-account
      responses:
        '201':
          description: Resource created successfully
      x-stoplight:
        id: m6bwe0k87hlgf
      tags:
        - PostCurrentAccount
    put:
      summary: Update current account
      operationId: put-current-account
      responses:
        '204':
          description: Resource updated successfully
      x-stoplight:
        id: kjywevt2p94l2
      description: ''
      tags:
        - PutCurrentAccount
    delete:
      summary: delete a current account
      operationId: delete-current-account
      responses:
        '204':
          description: Resource deleted successfully
      x-stoplight:
        id: 9ddolbrcq5rg4
      tags:
        - DeleteCurrentAccount
x-internal: true
tags:
  - name: GetCurrentAccount
