openapi: 3.0.1
x-stoplight:
  id: kbgyppvu32fiv
info:
  title: Current Account
  description: 'This service domain orchestrates a consumer checking/demand deposit account. The typical range of services and fees covers payments and deposits, standing orders, sweeps, liens, check and debit card access.'
  contact:
    name: C4E
    email: Dharamveer.1985@gmail.com
    url: 'https://www.demo.co.nz'
  version: 11.0.0
  license:
    url: 'https://www.demo.co.nz'
    name: Demo
servers:
  - url: 'https://virtserver.swaggerhub.com/current-account/api'
paths:
  '/current-account/{customerNumber}':
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Schema/GetCurrentAccount.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../../Common/BadRequest.yaml
        '401':
          description: UnAuthenticated error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnAuthenticated.yaml'
      operationId: get-current-account
      x-stoplight:
        id: 56dotah8tv67d
      description: Retrieve Information about the Current Account
      tags:
        - GetCurrentAccount
      x-internal: false
      requestBody:
        content: {}
    post:
      summary: create a new current
      operationId: post-current-account
      responses:
        '201':
          description: Resource created successfully
      x-stoplight:
        id: m6bwe0k87hlgf
      tags:
        - PostCurrentAccount
    put:
      summary: Update current account
      operationId: put-current-account
      responses:
        '204':
          description: Resource updated successfully
      x-stoplight:
        id: kjywevt2p94l2
      description: ''
      tags:
        - PutCurrentAccount
    delete:
      summary: delete a current account
      operationId: delete-current-account
      responses:
        '204':
          description: Resource deleted successfully
      x-stoplight:
        id: 9ddolbrcq5rg4
      tags:
        - DeleteCurrentAccount
    parameters:
      - schema:
          type: number
        name: customerNumber
        in: path
        required: true
        description: '123456789'
x-internal: true
tags:
  - name: GetCurrentAccount
components:
  schemas:
    UnAuthenticated.yaml:
      title: UnAuthenticated.yaml
      x-stoplight:
        id: jozpmpqthihb3
      type: object
      properties:
        errorCode:
          type: integer
          x-stoplight:
            id: w9uztvivhv5r4
          format: int32
          example: 401
        errorMessage:
          type: string
          x-stoplight:
            id: 36wttgj08lxkr
          example: UnAuthenticated
      required:
        - errorCode
        - errorMessage
      x-examples:
        Example 1:
          errorCode: 401
          errorMessage: UnAuthenticated
      description: The HyperText Transfer Protocol (HTTP) 401 Unauthorized response status code indicates that the client request has not been completed because it lacks valid authentication credentials for the requested resource.
    OrphanModel.yaml:
      title: OrphanModel.yaml
      x-stoplight:
        id: a7ztssppk4iqq
      type: object
      properties:
        status:
          type: string
          x-stoplight:
            id: 2qkbnu8g82bb1
      description: Not used model
